### ISSUE TITLE
Bots should "give up" when they cannot reach an item

### ISSUE THREAD

**Issue by warestarstuff** [randomperson189/ZSBots#7]
![image](https://user-images.githubusercontent.com/36561313/81626689-6a0af000-93ca-11ea-8fcc-f6a5858c5cfc.png)
I think this screenshot sums up the issue.

**Comment by randomperson189** [comment]
Agreed, I'll do that right now.

**Comment by randomperson189** [comment]
Alright I've fixed it now.
